### ISSUE TITLE
🐛...Hello developer, I still feel that the conflict between the plug-in and the Hover Editor is very influential during the use. The official page preview function is still too simple, and there are some other problems.   

### ISSUE THREAD

**Issue by lxmwwl** [jparkerweb/rich-foot#59]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or any example vault (.zip) to help explain your problem.

**Environment:**
 - OS: [e.g. Windows, MacOS, Linux, etc.]
 - Obsidian Version (if applicable): [e.g. 1.7.7, 1.8.1, etc.]
 - Other Details: 

**Additional context**

**Comment by owlethereal** [comment]
I have the same problem!

Describe the bug
When hovering the cursor on a back/outlink the preview doesn't show and the text twitches up and down

Steps to reproduce the behavior:

1- Enable "hover editor" plugin
2- Hover the cursor on any backlink or outlink from the rich footnote

Expected behavior
If hover editor is disabled, when the cursor is on a back/outlink it previews the note without any problem.

I suggest adding an option to not preview the note while hovering the links. Even if the bug is fixed, I don't see the point to force preview the note, since I can do that holding Ctrl anyway.

Btw, thanks for making the plugin, I liked it a lot, I hope I can use it with hover editor

Environment:

OS: Windows 11
Obsidian Version (if applicable): 1.7.7

**Comment by jparkerweb** [comment]
I will keep this bug in the backlog for now, as this is a pretty complicated issue (Obsidian shadow DOM cleanup, etc.) that I won't have time to dive into anytime soon.

If anyone that is impacted by this has time to jump in, the help would be welcomed.

Thanks for the issue submission. 👍

**Comment by lxmwwl** [comment]
Good news, I don't know why, the latest version of this problem has been solved

**Comment by owlethereal** [comment]
When I updated obsdian to 1.8.4, I was able to hover to and click one time on a rich foot backlink. After that the problem persisted and I cannot even hover a rich foot link without glitching.

**Comment by Ejaydee** [comment]
here's the evidence as i have same issue

https://github.com/user-attachments/assets/1797b82f-e3de-4045-a0f9-711fe46c8a15

**Comment by Ejaydee** [comment]
Version Richfoot 10.1.9
Hover Editor plugin 0.11.26

My workaround is to use the native hover provided by obsidian but I really want to use Hover Editor.
